config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root 'pages#home'
  get 'users/profile', to: 'users#show', as: 'user_show'

  get 'users/styleguide' => 'users#styleguide', as: :signup

  resources :matches, only: [:new, :create, :destroy]
  resources :organization_campaigns, only: [:show]
  resources :recipients, only: [:index, :update]
  resources :users, only: [:index, :new, :create]

  namespace :orgadmin do
    root to: 'dashboard#index', via: 'get'
    resources :dashboard, only: [:index]
    resources :campaigns do
      collection do
        get :switch_current_campaign
      end
    end
    resources :import_sessions, only: [:new, :create]
    resource :mail, only: [] do
      resources :appeals, only: [:new, :create]
    end
    resources :memberships
    resources :org_admins, only: [:index, :create, :destroy]
    resources :organization_campaigns, only: [:create]
    resources :recipients, only: [:index, :edit, :update]
  end

  namespace :vcadmin do
    root to: 'dashboard#index', via: 'get'
    resources :campaigns do
      collection do
        get :switch_current_campaign
      end
    end
  end
end

app/models/recipient.rb
# == Schema Information
#
# Table name: recipients
#
#  id                  :integer          not null, primary key
#  first_name          :string
#  last_name           :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  age                 :integer
#  gender              :string
#  race                :string
#  size                :string
#  wish_list           :string
#  recipient_family_id :integer
#  membership_id       :integer
#  fulfilled           :boolean          default(FALSE)
#

class Recipient < ActiveRecord::Base
  belongs_to :recipient_family

  # This reference is filled in to create the match
  belongs_to :membership

  scope :matched, -> { where.not(membership_id: nil) }

  def name
    "#{first_name} #{last_name}"
  end

  # Race and size are only listed where relevant, for dolls and clothes respectively
  def other_details
    [race.blank? ? nil : "Race: #{race}",
     size.blank? ? nil : "Size: #{size}"].compact.join(', ')
  end

  def matched?
    membership_id.present?
  end
end

app/controllers/orgadmin/recipients_controller.rb
module Orgadmin
  class RecipientsController < Orgadmin::ApplicationController
    def index
      @oc = find_organization_campaign
      if params[:matched] == 'true'
        @recipients = @oc.matched_recipients
      elsif params[:matched] == 'false'
        @recipients = @oc.unmatched_recipients
      else
        @recipients = @oc.recipients
      end
    end

    def edit
      @user = User.new
      @membership = Membership.new
      @recipient = Recipient.find(params[:id])
      @memberships = @org.memberships_sorted_by_name
    end

    def update
      recipient = Recipient.find(params[:id])
      recipient.update(membership_id: params[:recipient][:membership_id])
      redirect_to orgadmin_recipients_path
    end
  end
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  def update
    recipient = Recipient.find(params[:id])
    recipient.update(membership_id: params[:recipient][:membership_id])
    flash[:message] = "Thank you for helping #{recipient.first_name}!"
    redirect_to user_show_path
  end
end

app/views/recipients/_form.html.erb
<%= form_for @recipient do |f| %>
  <p>
    Campaign: <%= @recipient.organization_campaign.campaign_name %>
  </p>

  <%= f.hidden_field :recipient_family_id, value: @recipient.recipient_family.id %>

  <%= f.hidden_field :organization_campaign_id, value: @recipient.organization_campaign.id %>

  <%= label_tag :first_name %>
  <br>
  <%= f.text_field :first_name %>
  <br>

  <%= label_tag :last_name %>
  <br>
  <%= f.text_field :last_name %>
  <br>

  <%= label_tag :email %>
  <br>
  <%= f.text_field :email %>
  <br>

  <%= label_tag :street %>
  <br>
  <%= f.text_field :street %>
  <br>

  <%= label_tag :city %>
  <br>
  <%= f.text_field :city %>
  <br>

  <%= label_tag :state %>
  <br>
  <%= f.text_field :state %>
  <br>

  <%= label_tag :zip_code %>
  <br>
  <%= f.text_field :zip_code %>
  <br>

  <%= label_tag :age %>
  <br>
  <%= f.text_field :age %>
  <br>

  <%= label_tag :gender %>
  <br>
  <%= f.text_field :gender %>
  <br>

  <%= label_tag :race %>
  <br>
  <%= f.text_field :race %>
  <br>

  <%= label_tag :size %>
  <br>
  <%= f.text_field :size %>
  <br>

  <%= label_tag :wish_list %>
  <br>
  <%= f.text_field :wish_list %>
  <br>

  <p>
    Recipient family: <%= "#{@recipient.recipient_family.contact_last_name} #{@recipient.recipient_family.contact_first_name} family" %>
  </p>

  <%= f.submit %>
<% end %>

app/views/recipients/new.html.erb
<h1>New Recipient<br/><small>for <%= "#{@recipient.recipient_family.contact_last_name} #{@recipient.recipient_family.contact_first_name} family" %></small></h1>

<%= render partial: 'form' %>

app/views/recipients/show.html.erb
<p>
  <%= "#{@recipient.first_name} #{@recipient.last_name} family" %>
  <% if current_user.has_role? :admin %>
    <%= link_to '<i class="glyphicon glyphicon-edit"></i>'.html_safe, edit_recipient_path(@recipient) %>
    <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, recipient_path(@recipient), method: :delete %>
  <% end %>
</p>

<p>
  Campaign: <%= @recipient.organization_campaign.campaign_name %>
</p>

<p>
  First name: <%= @recipient.first_name %>
</p>

<p>
  Last name: <%= @recipient.last_name %>
</p>

<p>
  Email: <%= @recipient.email %>
</p>

<p>
  Street: <%= @recipient.street %>
</p>

<p>
  City: <%= @recipient.city %>
</p>

<p>
  State: <%= @recipient.state %>
</p>

<p>
  Zip: <%= @recipient.zip_code %>
</p>

<p>
  Age: <%= @recipient.age %>
</p>

<p>
  Gender: <%= @recipient.gender %>
</p>

<p>
  Race: <%= @recipient.race %>
</p>

<p>
  Size: <%= @recipient.size %>
</p>

<p>
  Wish list: <%= @recipient.wish_list %>
</p>

<p>
  Recipient family: <%= link_to "#{@recipient.recipient_family.contact_last_name} #{@recipient.recipient_family.contact_first_name}",
                                recipient_family_path(@recipient.recipient_family) %>
</p>