config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root 'pages#home'
  get 'users/profile', to: 'users#show', as: 'user_show'

  get 'users/styleguide' => 'users#styleguide', as: :signup

  resources :matches, only: [:new, :create, :destroy]
  resources :organization_campaigns, only: [:show]
  resources :recipients, only: [:index, :update]
  resources :users, only: [:index, :new, :create]

  namespace :orgadmin do
    root to: 'dashboard#index', via: 'get'
    resources :dashboard, only: [:index]
    resources :campaigns do
      collection do
        get :switch_current_campaign
      end
    end
    resources :import_sessions, only: [:new, :create]
    resource :mail, only: [] do
      resources :appeals, only: [:new, :create]
    end
    resources :memberships
    resources :org_admins, only: [:index, :create, :destroy]
    resources :organization_campaigns, only: [:create]
    resources :recipients, only: [:index, :edit, :update]
  end

  namespace :vcadmin do
    root to: 'dashboard#index', via: 'get'
    resources :campaigns do
      collection do
        get :switch_current_campaign
      end
    end
  end
end

app/models/recipient_family.rb
# == Schema Information
#
# Table name: recipient_families
#
#  id                       :integer          not null, primary key
#  organization_campaign_id :integer
#  casenumber               :integer
#  contact_last_name        :string
#  contact_first_name       :string
#  address                  :string
#  city                     :string
#  state                    :string
#  zip                      :string
#  phone                    :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  campaign_id              :integer
#

class RecipientFamily < ActiveRecord::Base
  # A recipient family always belongs to a campaign
  belongs_to :campaign

  # A recipient family belongs to an organization campaign when they 
  # are assigned by the volunteer center.  It should always be the case
  # that the linked campaign here should match te campaign in the 
  # organization_campaign.
  belongs_to :organization_campaign

  # The individual members of the family
  has_many :recipients
end

app/controllers/recipient_families_controller.rb
class RecipientFamiliesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource except: [:index, :show]
  layout 'org_admin'

  def index
    @recipient_families = RecipientFamily.all
  end

  def show
    @recipient_family = RecipientFamily.find(params[:id])
    @other_active_campaigns = RecipientFamily.where.not(id: @recipient_family)
  end

  def new
    @recipient_family = RecipientFamily.new
  end

  def create
    @recipient_family = RecipientFamily.new(recipient_family_params)

    if @recipient_family.save
      flash[:success] = 'Recipient family created!'
      redirect_to @recipient_family
    else
      flash[:alert] = "Couldn't create campaign"
      render :edit
    end
  end

  def edit
    @recipient_family = RecipientFamily.find(params[:id])
  end

  def update
    @recipient_family = RecipientFamily.find(params[:id])
    if @recipient_family.update_attributes(recipient_family_params)
      flash[:success] = 'Recipient family updated!'
      redirect_to @recipient_family
    else
      flash[:alert] = "Couldn't update"
      render :edit
    end
  end

  def destroy
    @recipient_family = RecipientFamily.find(params[:id])

    if @recipient_family.delete
      flash[:success] = "#{@recipient_family.name} Deleted"
      redirect_to campaigns_path
    else
      flash[:alert] = "Couldn't delete"
      redirect_to :back
    end
  end

  def switch_current_campaign
    session[:current_campaign] = params[:campaign]
    redirect_to campaign_path params[:campaign]
  end

  private

  def recipient_family_params
    params.
        require(:recipient_family).
        permit(:contact_last_name, :contact_first_name, :address, :city, :state, :zip, :phone)
  end
end

app/views/recipient_families/_form.html.erb
<%= form_for @recipient_family do |f| %>
  <%= label_tag :contact_first_name %>
  <br>
  <%= f.text_field :contact_first_name %>
  <br>
  <%= label_tag :contact_last_name %>
  <br>
  <%= f.text_field :contact_last_name %>
  <br>
  <%= label_tag :address %>
  <br>
  <%= f.text_field :address %>
  <br>
  <%= label_tag :city %>
  <br>
  <%= f.text_field :city %>
  <br>
  <%= label_tag :state %>
  <br>
  <%= f.text_field :state %>
  <br>
  <%= label_tag :zip %>
  <br>
  <%= f.text_field :zip %>
  <br>
  <%= label_tag :phone %>
  <br>
  <%= f.text_field :phone %>
  <br>
  <%= f.submit %>
<% end %>

app/views/recipient_families/edit.html.erb
<h1>Edit <%= "#{@recipient_family.contact_last_name} #{@recipient_family.contact_first_name} family" %></h1>

<%= render partial: 'form' %>

app/views/recipient_families/index.html.erb
<% @recipient_families.each do |recipient_family| %>
    <%= link_to "#{recipient_family.contact_last_name} #{recipient_family.contact_first_name} family", recipient_family %>
    <% if current_user.has_role? :admin %>
        <%= link_to '<i class="glyphicon glyphicon-edit"></i>'.html_safe, edit_recipient_family_path(recipient_family) %>
        <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, recipient_family_path(recipient_family), method: :delete %>
    <% end %>
    <br>
<% end %>

<% if current_user.has_role? :admin %>
    <br>
    <br>
    <%= link_to 'Add new recipient family'.html_safe, new_recipient_family_path %>
<% end %>

app/views/recipient_families/new.html.erb
<h1>New Recipient Family</h1>

<%= render partial: 'form' %>

app/views/recipient_families/show.html.erb
<p>
  <%= "#{@recipient_family.contact_last_name} #{@recipient_family.contact_first_name} family" %>
  <% if current_user.has_role? :admin %>
    <%= link_to '<i class="glyphicon glyphicon-edit"></i>'.html_safe, edit_recipient_family_path(@recipient_family) %>
    <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, recipient_family_path(@recipient_family), method: :delete %>
  <% end %>
</p>

<p>
  <%= link_to 'Add a recipient', new_recipient_path(recipient_family: @recipient_family) %>
</p>

<p>
  <table class="table">
    <thead>
      <tr>
        <th>Recipients</th>
      </tr>
    </thead>
    <tbody>
    <% @recipient_family.recipients.each do |recipient| %>
        <tr>
          <td>
            <%= "#{recipient.first_name} #{recipient.last_name}" %>
          </td>
        </tr>
    <% end %>

    </tbody>
  </table>
</p>