config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root 'pages#home'
  get 'users/profile', to: 'users#show', as: 'user_show'

  get 'users/styleguide' => 'users#styleguide', as: :signup

  resources :matches, only: [:new, :create, :destroy]
  resources :organization_campaigns, only: [:show]
  resources :recipients, only: [:index, :update]
  resources :users, only: [:index, :new, :create]

  namespace :orgadmin do
    root to: 'dashboard#index', via: 'get'
    resources :dashboard, only: [:index]
    resources :campaigns do
      collection do
        get :switch_current_campaign
      end
    end
    resources :import_sessions, only: [:new, :create]
    resource :mail, only: [] do
      resources :appeals, only: [:new, :create]
    end
    resources :memberships
    resources :org_admins, only: [:index, :create, :destroy]
    resources :organization_campaigns, only: [:create]
    resources :recipients, only: [:index, :edit, :update]
  end

  namespace :vcadmin do
    root to: 'dashboard#index', via: 'get'
    resources :campaigns do
      collection do
        get :switch_current_campaign
      end
    end
  end
end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id                :integer          not null, primary key
#  name              :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  description       :text
#  logo_file_name    :string
#  logo_content_type :string
#  logo_file_size    :integer
#  logo_updated_at   :datetime
#  url               :string
#  slug              :string
#

class Organization < ActiveRecord::Base
  # Use rolify to enforce org admin rights to particular users
  resourcify

  has_many :organization_campaigns
  has_many :campaigns, through: :organization_campaigns

  has_many :memberships
  has_many :users, through: :memberships

  has_attached_file :logo,
                    styles: {
                      medium: '300x300>',
                      thumb: '100x100>'
                    },
                    default_url: '/images/:style/missing.png'

  validates_attachment_content_type :logo, content_type: %r{\Aimage\/.*\Z}

  extend FriendlyId
  friendly_id :name, use: :slugged

  # TODO: String based SQL is not portable - make this nicer
  def joinable_campaigns
    Campaign.currently_running.where(
      "NOT EXISTS (
        SELECT 'X'
          FROM organization_campaigns oc
          WHERE oc.campaign_id = campaigns.id
                AND oc.organization_id = ?
      )", id
    )
  end

  # If there are overlapping campaigns, returns the one furthest out.
  def current_campaign
    return nil if campaigns.empty?
    campaigns.order(donation_deadline: 'DESC').first
  end

  def memberships_sorted_by_name
    memberships.includes(:user).order('users.last_name, users.first_name')
  end

  def memberships_with_email
    memberships.includes(:user).where.not(users: { email: nil })
  end
end

app/views/organizations/_form.html.erb
<%= form_for @organization do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <div>
      <%= f.text_area :description %>
    </div>
  </div>

  <div>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <%= f.submit %>
<% end %>

app/views/organizations/edit.html.erb
<h1>Edit <%= @organization.name %></h1>

<%= render 'form' %>

app/views/organizations/index.html.erb
<h1>All Organizations</h1>

<table class="table table-striped">
  <thead>
    <th>Name</th>
    <th>Description</th>
    <th>URL</th>
    <th></th>
    <% if can? :manage, Organization %>
      <th></th>
    <% end %>
  </thead>
  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= link_to organization.name, organization_path(organization.id) %></td>
        <td><%= organization.description %></td>
        <td><%= link_to organization.url %></td>
        <td><%= link_to 'Details', organization, class: 'btn btn-default' %></td>
        <% if can? :manage, @organization %>
          <td><%= link_to 'Edit', edit_organization_path(organization), class: 'btn btn-primary' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @organizations %>

app/views/organizations/new.html.erb
<h1>Create New Organization</h1>

<%= render 'form' %>