config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root 'pages#home'
  get 'users/profile', to: 'users#show', as: 'user_show'

  get 'users/styleguide' => 'users#styleguide', as: :signup

  resources :matches, only: [:new, :create, :destroy]
  resources :organization_campaigns, only: [:show]
  resources :recipients, only: [:index, :update]
  resources :users, only: [:index, :new, :create]

  namespace :orgadmin do
    root to: 'dashboard#index', via: 'get'
    resources :dashboard, only: [:index]
    resources :campaigns do
      collection do
        get :switch_current_campaign
      end
    end
    resources :import_sessions, only: [:new, :create]
    resource :mail, only: [] do
      resources :appeals, only: [:new, :create]
    end
    resources :memberships
    resources :org_admins, only: [:index, :create, :destroy]
    resources :organization_campaigns, only: [:create]
    resources :recipients, only: [:index, :edit, :update]
  end

  namespace :vcadmin do
    root to: 'dashboard#index', via: 'get'
    resources :campaigns do
      collection do
        get :switch_current_campaign
      end
    end
  end
end

app/views/layouts/_admin_dropdown.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to :Organizations, '#' %>
    </li>

    <li role="separator" class="divider"></li>
    <li>
      <%= link_to :Campaigns, vcadmin_campaigns_path %>
    </li>
  </ul>
</li>

app/views/layouts/_flash.html.erb
<% if flash.present? %>
  <div id="flash-messages">
    <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %>">
        <button class="close" data-dismiss="alert">x</button>
        <%= message %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if session[:organization_name] %>
        <a class="navbar-brand" href="#"><%= session[:organization_name] %></a>
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      	<% if signed_in? %>
	      	<li><%= link_to current_user.email, edit_user_registration_path %></li>
    	    <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% if current_user.has_role? :admin %>
            <%= render 'layouts/admin_dropdown' %>
          <% end %>
          <li><%= link_to "Organization Admin", orgadmin_root_path %></li>
    		<% else %>
        	<li><%= link_to "Sign in", new_user_session_path %></li>
    		<% end %>
      </ul><!-- /.login toolbar -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShareChristmas</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag 'application.print', media: 'print' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body id="<%= params[:controller].parameterize %>_controller">
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/flash' %>
  <div class="container">
    <% if defined?(@organization_campaign) && @organization_campaign.try(:campaign_logo) %>
      <%= image_tag(@organization_campaign.campaign_logo.url, alt: "Logo", class: "header--logo") %>
    <% end %>
    <% if session[:organization_name] %>
      <h1 class="header"><%= session[:organization_name] %></h1>
    <% end %>
    <%= content_for?(:content) ? yield(:content) : yield %>
  </div>
  <%= javascript_include_tag 'application' %>
  <% if printer_friendly_request? %>
    <script type="text/javascript">
      window.onload = function() {
        window.print();
      };
    </script>
  <% end %>
</body>
</html>

app/views/layouts/org_admin.html.erb
<% content_for :content do %>
  <div class="container">
    <%= yield %>
  </div>
<% end %>
<%= render template: "layouts/application" %>